# Generated by Django 5.0.2 on 2026-10-02 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя компонента')),
                ('version', models.CharField(default='1.0', max_length=32, verbose_name='Версия')),
                ('expected_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Укажи SHA-256: 64 символа от 0 до 9 и от a до f.', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='Доверенный SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100, verbose_name='Имя компонента')),
                ('version', models.CharField(blank=True, max_length=32, verbose_name='Версия')),
                ('expected_hash', models.CharField(blank=True, max_length=64, verbose_name='Эталонный SHA-256')),
                ('actual_hash', models.CharField(blank=True, max_length=64, verbose_name='Фактический SHA-256')),
                ('verdict', models.CharField(choices=[('TRUSTED', 'TRUSTED'), ('UNTRUSTED', 'UNTRUSTED'), ('VERIFICATION_ERROR', 'VERIFICATION_ERROR')], max_length=20, verbose_name='Вердикт')),
                ('action', models.CharField(choices=[('ALLOWED', 'Разрешено'), ('BLOCKED', 'Заблокировано')], max_length=10, verbose_name='Решение')),
                ('operation', models.CharField(choices=[('CHECK', 'Проверка'), ('DEMO_START', 'Учебный запуск')], default='CHECK', max_length=12, verbose_name='Операция')),
                ('actor', models.CharField(default='anonymous', max_length=150, verbose_name='Инициатор')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='integrity.component')),
            ],
            options={
                'verbose_name': 'Событие проверки',
                'verbose_name_plural': 'Журнал проверок',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
